# Generated by Django 5.0.7 on 2024-07-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_type_alter_job_creationdate_job_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_type',
            old_name='Job_type',
            new_name='job_type',
        ),
    ]
