# Generated by Django 5.0.7 on 2024-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_joblocation_job_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.ManyToManyField(to='job.experience'),
        ),
    ]
