# Generated by Django 5.0.7 on 2024-07-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_remove_employers_type_remove_jobseekers_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
