# Generated by Django 5.0.7 on 2024-07-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_job_experience_job_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='is_employer',
        ),
        migrations.RemoveField(
            model_name='jobseekers',
            name='is_student',
        ),
        migrations.AddField(
            model_name='employers',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
