# Generated by Django 5.0.7 on 2024-07-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
    ]
