# Generated by Django 5.0.7 on 2024-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_remove_job_job_location_delete_joblocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='company_des',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
