# Generated by Django 5.0.7 on 2024-07-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_educationexperience_required_knowledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joblocation', models.CharField(max_length=50)),
            ],
        ),
    ]
