# Generated by Django 5.0.7 on 2024-07-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0023_educations_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='job',
        ),
        migrations.DeleteModel(
            name='Educations',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
    ]
