# Generated by Django 5.0.7 on 2024-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_rename_gender_employers_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='start_date',
        ),
        migrations.AddField(
            model_name='job',
            name='vacency',
            field=models.IntegerField(null=True),
        ),
    ]
