# Generated by Django 5.0.7 on 2024-07-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_remove_job_start_date_job_vacency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Later',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobseekers')),
            ],
        ),
    ]
