# Generated by Django 5.0.7 on 2024-07-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_alter_job_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experiences',
        ),
    ]
