# Generated by Django 5.0.7 on 2024-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_required_knowledge_requirement2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationexperience',
            name='education1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='education2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='education3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='education4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
