# Generated by Django 5.0.6 on 2024-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_alter_employers_web_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
