# Generated by Django 5.0.7 on 2024-08-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_alter_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
